### ISSUE TITLE
modernx.conf doesn't work with your fork

### ISSUE THREAD

**Issue by vvt4** [zydezu/mpvconfig#11]
Set up modernx.conf as instructed by the readme. No changes in behaviour whatsoever.

**Comment by zydezu** [comment]
Do any errors register when you run mpv in the command line? What is your folder structure? Thanks !

**Comment by vvt4** [comment]
`[modernx] script-opts/modernx.conf:1 unknown key 'local user_opts ', ignoring
[modernx] script-opts/modernx.conf:2 unknown key '      titlefontsize', ignoring
[modernx] script-opts/modernx.conf:3 unknown key '      welcomescreen', ignoring
[modernx] script-opts/modernx.conf:4 unknown key '      noxmas', ignoring
[modernx] script-opts/modernx.conf:5 unknown key '      windowcontrols', ignoring
[modernx] script-opts/modernx.conf:6 unknown key '      vidscale', ignoring
[modernx] script-opts/modernx.conf:7 unknown key '      scalewindowed ', ignoring
[modernx] script-opts/modernx.conf:8 unknown key '      scalefullscreen ', ignoring
[modernx] script-opts/modernx.conf:9 unknown key '      scaleforcedwindow ', ignoring
[modernx] script-opts/modernx.conf:10 unknown key '     bottomhover', ignoring
[modernx] script-opts/modernx.conf:11 unknown key '     raisesubswithosc', ignoring
[modernx] script-opts/modernx.conf:12 unknown key '     showdescription', ignoring
[modernx] script-opts/modernx.conf:13 unknown key '     showwindowtitle', ignoring
[modernx] script-opts/modernx.conf:14 unknown key '     seekbarfg_color', ignoring
[modernx] script-opts/modernx.conf:15 unknown key '     iconstyle', ignoring
[modernx] script-opts/modernx.conf:16 unknown key '     compactmode', ignoring`

I get this. Folder structure for the config is C:\Users\User\AppData\Roaming\mpv\script-opts\modernx.conf

**Comment by zydezu** [comment]
Please can you send me your `modernx.conf` file

**Comment by zydezu** [comment]
Text in the conf file should be formatted as such: 
```
compactmode=no
showinfo=yes
titlefontsize=20
seekbarhandlesize=0
```
these suggest either an error in the conf file or the modernx.lua file itself

**Comment by vvt4** [comment]
> Text in the conf file should be formatted as such:
> 
> ```
> compactmode=no
> showinfo=yes
> titlefontsize=20
> seekbarhandlesize=0
> ```
> 
> these suggest either an error in the conf file or the modernx.lua file itself

Yeah the format should've been like that I fixed it. Thanks. Was using true/false instead of yes/no also I'd like to point out that for the color change params, it's not necessary to include "#" (quotations or hashtags). `seekbarfg_color=FFFFFF` works.
