### ISSUE TITLE
The video description of online videos does not support Chinese, which displays garbled characters

### ISSUE THREAD

**Issue by zydezu** [zydezu/mpvconfig#12]
https://github.com/cyl0/ModernX/issues/66
![image](https://github.com/zydezu/mpvconfig/assets/50119098/3a45c4da-e3ad-4bdc-b6e6-5912bc4a48a3)

As shown in the figure, the Chinese language involved in watching online videos cannot be displayed properly. I am not sure if it is possible to add support for Chinese language. Thank you very much

**Comment by ywq0056** [comment]
Sorry, due to my negligence, I sent it to the wrong location and it should have been posted here. I have always used your version

**Comment by zydezu** [comment]
I’ve known this problem for a while, CJK characters (and other various unicode characters) don’t get outputted correctly by kia’s subprocess command, as they don’t pay any attention to text formatting- it must be done manually. I’ll have to figure this out…

**Comment by zydezu** [comment]
> Sorry, due to my negligence, I sent it to the wrong location and it should have been posted here. I have always used your version

I believe this has been fixed in the latest commit !! https://github.com/zydezu/mpvconfig/commit/1cf89ce6692dd8a7a9071a58d27a60ed422ed47c

**Comment by zydezu** [comment]
![2024-01-25_17-10-50_410_mpv](https://github.com/zydezu/mpvconfig/assets/50119098/c665ec8f-a7b4-4323-b5d2-1bdfcf0d7dcb)
