### ISSUE TITLE
Seekbarhandle does not hit the end position

### ISSUE THREAD

**Issue by yukina3230** [zydezu/mpvconfig#3]
When video ended, the handle's max position didn't hit the end of seekbar, the gap is more visible when dragging the handle.

[Screencast from 2023-09-17 11-47-49.webm](https://github.com/zydezu/mpvconfig/assets/75545944/702b162f-04f7-46dd-a4a1-d689cd99ca18)

**Comment by zydezu** [comment]
This should be fixed in the latest commit > https://github.com/zydezu/mpvconfig/commit/e08e0d43558a7e92b7e1e14f231122a466454d9f
