### ISSUE TITLE
Mute button not working as expected

### ISSUE THREAD

**Issue by carycary246** [zydezu/mpvconfig#5]
The mute button seems to set volume to 0 instead of muting. When enabling sound, it will set volume to 20 instead of the original volume it was at.

It works fine in the original fork here https://github.com/maoiscat/mpv-osc-modern. Clicking mute will turn off the sound and enabling will return to original volume.

**Comment by zydezu** [comment]
This has been fixed in the latest commit! https://github.com/zydezu/mpvconfig/commit/6da8253eb02190859fbb0e789f3e0e87a2042ce9 A release including these fixes will be coming soon...
