### ISSUE TITLE
error loading modernx.lua with mpv v0.37.0-7

### ISSUE THREAD

**Issue by Lovecraft-github** [zydezu/mpvconfig#6]
With the latest mpv builds the modernx didn't load and return this message in console
`          modernx: 
          modernx: stack traceback:
          modernx: 	/home/user/.config/mpv/scripts/modernx.lua:3269: in function 'visibility_mode'
          modernx: 	/home/user/.config/mpv/scripts/modernx.lua:2666: in function 'prop'
          modernx: 	mp.defaults:409: in function 'handler'
          modernx: 	mp.defaults:512: in function 'call_event_handlers'
          modernx: 	mp.defaults:554: in function 'dispatch_events'
          modernx: 	mp.defaults:505: in function <mp.defaults:504>
          modernx: 	[C]: in ?
          modernx: 	[C]: in ?
          modernx: Lua error: /home/user/.config/mpv/scripts/modernx.lua:3269: attempt to call field 'shared_script_property_set' (a nil value)`

mpv v0.37.0-7-g86b498ecc0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov 22 2023 17:27:28
libplacebo version: v6.338.0-58-g2385b367
FFmpeg version: N-112826-g707e46dc54
FFmpeg library versions:
   libavutil       58.32.100
   libavcodec      60.34.100
   libavformat     60.17.100
   libswscale      7.6.100
   libavfilter     9.13.100
   libswresample   4.13.100

start happening after this commit
[player: remove shared-script-properties property ](https://github.com/mpv-player/mpv/commit/86b498ecc0e6276bb905df57f479d0506b45ba53)

**Comment by zydezu** [comment]
Does https://github.com/zydezu/mpvconfig/commit/4751dbad72e0352b01061a9928b285944c20719d fix this?

**Comment by Lovecraft-github** [comment]
> Does [4751dba](https://github.com/zydezu/mpvconfig/commit/4751dbad72e0352b01061a9928b285944c20719d) fix this?

Yes it does

We can mark it closed, right?

Thank you

**Comment by Lovecraft-github** [comment]
Yes it does

We can mark it closed, right?

Thank you
