### ISSUE TITLE
[modernx 0.2.3] The OSC doesn't hide

### ISSUE THREAD

**Issue by Keith94** [zydezu/mpvconfig#7]
Worked fine in [0.2.2.5](https://github.com/zydezu/ModernX/releases/tag/0.2.2.5)

**Comment by zydezu** [comment]
Do you have any config settings?

**Comment by Keith94** [comment]
Oh, I had set `bottomhover=no` in modernx.conf. Seems it was breaking the OSC hiding properly.

**Comment by zydezu** [comment]
This has been fixed in the latest commit! https://github.com/zydezu/mpvconfig/commit/4073ae9aedeb0ed8b102e1dbf0d4dad983952374

**Comment by Keith94** [comment]
Thanks for the quick fix
