### ISSUE TITLE
OSC controls doesn't work with online videos after last ModernX update

### ISSUE THREAD

**Issue by Lovecraft-github** [zydezu/mpvconfig#8]
When load a (for example) YouTube video, the modernx OSC doesn't show up. It works well with local files.
The console show this message

     modernx: 
     modernx: stack traceback:
     modernx:   /home/user/.config/mpv/scripts/modernx.lua:1137: in function 'format_file_size'
     modernx:   /home/user/.config/mpv/scripts/modernx.lua:1145: in function 'checktitle'
     modernx:   /home/user/.config/mpv/scripts/modernx.lua:1049: in function 'handler'
     modernx:   mp.defaults:512: in function 'call_event_handlers'
     modernx:   mp.defaults:554: in function 'dispatch_events'
     modernx:   mp.defaults:505: in function <mp.defaults:504>
     modernx:   [C]: in ?
     modernx:   [C]: in ?
     modernx: Lua error: /home/user/.config/mpv/scripts/modernx.lua:1137: attempt to compare number with nil

I started noticed it after [06b1960](https://github.com/zydezu/mpvconfig/commit/06b19606f34e10471f4ed612b33797f2dd112252)

last working [make dates on their own in description clickable](https://github.com/zydezu/mpvconfig/commit/6c22d33caadbe09af6daceb43ca1b5cd668e2ec2)
[6c22d33](https://github.com/zydezu/mpvconfig/commit/6c22d33caadbe09af6daceb43ca1b5cd668e2ec2)

**Comment by zydezu** [comment]
This should’ve been fixed in the latest commit. I apologise.

**Comment by Lovecraft-github** [comment]
Thanks for the fix.
