### ISSUE TITLE
[bug] "persistantprogress" function.

### ISSUE THREAD

**Issue by SalehA-55** [zydezu/mpvconfig#9]
I was thrilled to see "persistantprogress" finally land in mpv! especially after I put up a suggestion for it in another (dead?) repository. Anyway, thanks for implementing it.

Having trouble getting it to display consistently though. It only appears while the OSC is visible. Any solutions or potential workarounds? 

This is what I get:

"when OSC is visible" (green arrow indicating what shows with "persistantprogress = true")
![Screenshot 2024-01-04 132940 (1)](https://github.com/zydezu/mpvconfig/assets/120289546/2271e21d-bd1e-472d-a011-db170dd8a01f)

"when OSC is NOT visible"
![Screenshot 2024-01-04 132944](https://github.com/zydezu/mpvconfig/assets/120289546/9af1a2d8-97e1-44f3-b671-1704d9effe66)

**Comment by zydezu** [comment]
Apologies… I think I started working on this feature then forgot halfway through… I’m sorry but it’s not ready as of now. I’ll see if I can implement it soon :]

**Comment by zydezu** [comment]
This has been implemented in the latest commit --- the options `persistentprogress` and `persistentbuffer` are now available!
![2024-01-12_08-47-05_210_mpv](https://github.com/zydezu/mpvconfig/assets/50119098/2429d5f2-ff85-46e6-bd69-cf2a3f1f3b31)
Please let me know of any bugs ^_^

**Comment by zydezu** [comment]
https://github.com/zydezu/mpvconfig/commit/4e2c60ffadd238f307558bdb849380978cc58b3f

**Comment by zydezu** [comment]
Added the `persistentprogressheight` option in this commit - https://github.com/zydezu/mpvconfig/commit/4e2c60ffadd238f307558bdb849380978cc58b3f

**Comment by SalehA-55** [comment]
Hey, I love the implementation and am very thankful.

I was wondering if you can add the option to toggle the "persistantprogress" as a key binding?
Something like "V" for toggling subtitles viability.

**Comment by zydezu** [comment]
This has been added in the latest commit (and release) with the 'b' key :)

**Comment by zydezu** [comment]
Thanks for the fix! Sorry I have seen this so late, but I'm glad your enjoying the config! 
https://github.com/zydezu/mpvconfig/commit/7d4f6602eafbedbe49c4d2c0aaf174d6a614438d
